### ISSUE TITLE
LibreQoS.py - validation error

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#116]
I install testing envirnoment and do some tests:

```
# ./LibreQoS.py 
refreshShapers starting at 22/09/2022 09:46:55
Not first time run since system boot.
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
NIC queues:			1
CPU cores:			8
queuesAvailable set to:	1
Traceback (most recent call last):
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 864, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 606, in refreshShapers
    traverseNetwork(network)
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 578, in traverseNetwork
    comment = comment + '| Comment: ' + device['comment']
KeyError: 'comment'
```

generates an error with ShapedDevices.csv file like:
```
Circuit ID,Circuit Name,Device ID,Device Name,Parent Node,MAC,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max,Comment
,"968 Circle St., Gurnee, IL 60031",1,Device 1,,,"10.0.0.1, 10.0.0.2",,25,5,155,20,
,"31 Marconi Street, Lake In The Hills, IL 60156",2,Device 2,,,10.0.0.3,,25,5,105,18,
```

cat network.json 
```
{
}
```

What is wrong with that? (its almost an example)

**Comment by interduo** [comment]
Thanks! :)
