### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by eth0rob** [rchac/LibreQoS#31]
uname -a
Linux qos-box 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Python script doesnt start, following error

/usr/bin/python3 LibreQoS.py 

Traceback (most recent call last):
  File "/home/uberadmin/LibreQoS/v1.0/LibreQoS.py", line 330, in <module>
    refreshShapers()
  File "/home/uberadmin/LibreQoS/v1.0/LibreQoS.py", line 254, in refreshShapers
    print(tabs + '   ', end='')
NameError: name 'tabs' is not defined

**Comment by rchac** [comment]
Thank you for making us aware of this. Looks like some code from v1.1 was accidentally copied in regarding tab spacing (my error, sorry). Could you please try re-downloading v1.0 and seeing if it works for you now?

**Comment by drumbum85** [comment]
uname -a
Linux server 5.13.0-44-generic #49-Ubuntu SMP Wed May 18 13:28:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I have a similar error, trying to run v1.1

/usr/bin/python3 LibreQoS.py

Traceback (most recent call last):
  File "/home/david/LibreQoS/v1.1/LibreQoS.py", line 253, in <module>
    refreshShapers()
  File "/home/david/LibreQoS/v1.1/LibreQoS.py", line 73, in refreshShapers
    network = json.loads(j.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 17 column 6 (char 285)

I can't figure out which file I'm supposed to be looking for, maybe I messed up my config, json, or csv?

**Comment by fatbum85** [comment]
Turns out it's my network.json. Go figure. Will try again.
