### ISSUE TITLE
[v1.1] LibreQoS.py: validation error

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#51]
I've got flat design (only subscriber queues) but I would like to ommit tc single_lock bottleneck so I created 4 sites:

cat network.json 
```
{
	"INTERDUO1":
	{
	  "downloadBandwidthMbps":5000,
  	  "uploadBandwidthMbps":5000,
	}
	"INTERDUO2":
	{
	  "downloadBandwidthMbps":5000,
  	  "uploadBandwidthMbps":5000,
	}
	"INTERDUO3":
	{
	  "downloadBandwidthMbps":5000,
  	  "uploadBandwidthMbps":5000,
	}
	"INTERDUO4":
	{
	  "downloadBandwidthMbps":5000,
  	  "uploadBandwidthMbps":5000,
	}
}
```
cat Shaper.csv 
```
ID,AP,MAC,Hostname,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max
,INTERDUO1,,Device 1,100.64.0.1,,25,5,155,20
,INTERDUO1,,Device 2,100.64.0.2,,25,5,105,18
,INTERDUO2,,Device 3,100.64.0.3,,25,5,105,18
,INTERDUO2,,Device 4,100.64.0.4,,25,5,105,18
,INTERDUO3,,Device 5,100.64.0.5,,25,5,105,18
,INTERDUO3,,Device 6,100.64.0.6,,25,5,90,15
,INTERDUO4,,Device 7,100.64.0.7,,25,5,155,20
,INTERDUO4,,Device 8,100.64.0.8,,25,5,105,18
,INTERDUO1,,Device 9,100.64.0.9,,25,5,105,18
,INTERDUO1,,Device 10,100.64.0.10,,25,5,105,18
,INTERDUO2,,Device 11,100.64.0.11,,25,5,105,18
```

python3 LibreQoS.py gives me
```
Traceback (most recent call last):
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 243, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 72, in refreshShapers
    network = json.loads(j.read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
```

**Comment by interduo** [comment]
cat network.json 
```
{
	"INTERDUO1":
                   {
                   "downloadBandwidthMbps":5000,
                   "uploadBandwidthMbps":5000
                   },
	"INTERDUO2":
                   {
                   "downloadBandwidthMbps":5000,
                   "uploadBandwidthMbps":5000
                   },
	"INTERDUO3":
                   {
                   "downloadBandwidthMbps":5000,
                   "uploadBandwidthMbps":5000
                   },
	"INTERDUO4":
                   {
                   "downloadBandwidthMbps":5000,
                   "uploadBandwidthMbps":5000
                   }
}
```

and now works.

**Comment by marsalans** [comment]
Have you tested it, what is the result with subscribers ?
