### ISSUE TITLE
UISP integration error

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#87]
I don't use UISP so I commented out:

ispConfig.py
```
# Optional UISP integration
automaticImportUISP = False

# Everything before /nms/ on your UISP instance
# uispBaseURL = 'https://examplesite.com'
# UISP Auth Token
# uispAuthToken = ''
# UISP | Whether to shape router at customer premises, or instead shape the station radio. When station radio is in
# router mode, use 'station'. Otherwise, use 'router'.
# sapeRouterOrStation = 'router'
# List any sites that should not be included, with each site name surrounded by '' and seperated by commas
#excludeSites = []

```

When start I've got an error:
```
Sep 12 17:57:55 rty-libreqos systemd[1]: Started LibreQoS.service.
Sep 12 17:57:55 rty-libreqos python3[32828]: Traceback (most recent call last):
Sep 12 17:57:55 rty-libreqos python3[32828]:   File "/root/LibreQoS2/v1.2/scheduled.py", line 7, in <module>
Sep 12 17:57:55 rty-libreqos python3[32828]:     from integrationUISP import importFromUISP
Sep 12 17:57:55 rty-libreqos python3[32828]:   File "/root/LibreQoS2/v1.2/integrationUISP.py", line 5, in <module>
Sep 12 17:57:55 rty-libreqos python3[32828]:     from ispConfig import UISPbaseURL, uispAuthToken, shapeRouterOrStation, allowedSubnets, ignoreSubnets, e>
Sep 12 17:57:55 rty-libreqos python3[32828]: ImportError: cannot import name 'UISPbaseURL' from 'ispConfig' (/root/LibreQoS2/v1.2/ispConfig.py)
Sep 12 17:57:55 rty-libreqos systemd[1]: LibreQoS.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by rchac** [comment]
Did https://github.com/rchac/LibreQoS/commit/6115b5852b5509d909d0ac0d80451cb4aedd9345 help?

**Comment by interduo** [comment]
Yes. Thanks for fast reaction.
