### ISSUE TITLE
comments of the classes - need more improvement, class statistics for IP

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#94]
linux_tc.txt is now:

`class add dev ens16np0 parent 0x9:0x4fb classid 0x565 htb rate 545mbit ceil 545mbit prio 3 # CircuitID: 17932`

we consider to be:
`class add dev ens16np0 parent 0x9:0x4fb classid 0x565 htb rate 545mbit ceil 545mbit prio 3 # CircuitID: 17932, DeviceID: 1234,3334 `
or
`class add dev ens16np0 parent 0x9:0x4fb classid 0x565 htb rate 545mbit ceil 545mbit prio 3 # CircuitID: 17932, COMMENT FROM LAST COLUMN`

It would be very helpful because now we every time we need to check some tc class statistics  for some DeviceID we  firstly need to grep it from `ShapedDevices.csv` and then check linux_tc.txt and then check statistics.

Maybe `LibreQoS.py --tc-statistics-from-ip 172.20.20.30` could show use statistic for classid 0x565 on both interfaces?

**Comment by rchac** [comment]
Added deviceID and comment to comments in linux tc commands. https://github.com/rchac/LibreQoS/commit/6f2398e665ee82a7aa1f395d34ea184ee6595a75

> Maybe `LibreQoS.py --tc-statistics-from-ip 172.20.20.30` could show use statistic for classid 0x565 on both interfaces?

Ok. Working on it

**Comment by interduo** [comment]
to much newline symbols but this is super feature! :)

**Comment by interduo** [comment]
./LibreQoS.py --tc-statistics-from-ip=172.20.2.42

```
qdisc cake ce5e: parent 11:a15 bandwidth unlimited diffserv4 triple-isolate nonat nowash no-ack-filter split-gso rtt 100ms raw overhead 0 

 Sent 63971215 bytes 58194 pkt (dropped 1, overlimits 0 requeues 0) 

 backlog 0b 0p requeues 0

 memory used: 2363136b of 15140Kb

 capacity estimate: 0bit

 min/max network layer size:           60 /    1514

 min/max overhead-adjusted size:       60 /    1514

 average network hdr offset:           14



                   Bulk  Best Effort        Video        Voice

  thresh           0bit         0bit         0bit         0bit

  target            5ms          5ms          5ms          5ms

  interval        100ms        100ms        100ms        100ms

  pk_delay          0us         37us          0us          0us

  av_delay          0us          6us          0us          0us

  sp_delay          0us          0us          0us          0us

  backlog            0b           0b           0b           0b

  pkts                0        58195            0            0

  bytes               0     63972705            0            0

  way_inds            0            0            0            0

  way_miss            0          162            0            0

  way_cols            0            0            0            0

  drops               0            1            0            0

  marks               0            0            0            0

  ack_drop            0            0            0            0

  sp_flows            0            1            0            0

  bk_flows            0            1            0            0

  un_flows            0            0            0            0

  max_len             0         1514            0            0

  quantum          1514         1514         1514         1514



qdisc cake ce5f: parent 11:a15 bandwidth unlimited diffserv4 triple-isolate nonat nowash no-ack-filter split-gso rtt 100ms raw overhead 0 

 Sent 4421484 bytes 19800 pkt (dropped 0, overlimits 0 requeues 0) 

 backlog 0b 0p requeues 0

 memory used: 26112b of 15140Kb

 capacity estimate: 0bit

 min/max network layer size:           60 /    1514

 min/max overhead-adjusted size:       60 /    1514

 average network hdr offset:           14



                   Bulk  Best Effort        Video        Voice

  thresh           0bit         0bit         0bit         0bit

  target            5ms          5ms          5ms          5ms

  interval        100ms        100ms        100ms        100ms

  pk_delay          0us         13us          2us          1us

  av_delay          0us          2us          0us          0us

  sp_delay          0us          0us          0us          0us

  backlog            0b           0b           0b           0b

  pkts                0        19793            1            6

  bytes               0      4420739           90          655

  way_inds            0            0            0            0

  way_miss            0          167            1            2

  way_cols            0            0            0            0

  drops               0            0            0            0

  marks               0            0            0            0

  ack_drop            0            0            0            0

  sp_flows            0            2            0            2

  bk_flows            0            1            0            0

  un_flows            0            0            0            0

  max_len             0         1514           90          121

  quantum          1514         1514         1514         1514

```

**Comment by rchac** [comment]
> to much newline symbols but this is super feature! :)

Fixed https://github.com/rchac/LibreQoS/commit/ac79581c95ed1a62986b6c24609716f3725f36b4

**Comment by interduo** [comment]
Now it has got really nice output. Thanks.

**Comment by interduo** [comment]
Error
```
# ./LibreQoS.py --tc-statistics-from-ip=172.20.2.42
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 799, in <module>
    printStatsFromIP(args.tc_statistics_from_ip)
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 78, in printStatsFromIP
    subscriberCircuits = json.loads(j.read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 1006799 (char 1006798)
```

**Comment by interduo** [comment]
ok - just needs to be done with double quotes
